refactor, feat: add likes and friends
DZaparov/java-filmorate pull request #7
Opened 2024-01-28 23:05 UTC by DZaparov

2024-01-29 06:00 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +@ControllerAdvice
Лучше воспользоваться `@RestControllerAdvice` (на курсе он рекомендован)

2024-01-29 06:01 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +}
Нужно добавить обработку Throwable в 500 ый статус (INTERNAL_SERVER_ERROR)

2024-01-29 06:06 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public void validateUser(User user) {
Попробуй вместо валидации методом validateUser настроить валидацию с помощью аннотации `@Valid` в методах контроллеров

2024-01-29 06:06 UTC, VadimZharkov requested changes
Можно улучшить

2024-01-29 07:23 UTC, DZaparov commented
Привет! Я просто убрал метод validUser и validFilm, ведь на сколько я понял @Valid уже был настроен) А валидацию из метода убрал в тесты. Надеюсь правильно)

2024-01-29 12:26 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        return Map.of("error", "Ошибка валидации.",
Мар - слишком обезлченный тип. Лучше сделать класс ErrorResponse и в методах обработчика ошибок его отдавать. Например
```
	@ExceptionHandler
	@ResponseStatus(HttpStatus.NOT_FOUND)
	public ErrorResponse handleNotFoundException(final DataNotFoundException e) {
		log.info("404 {}", e.getMessage());
		return new ErrorResponse(e.getMessage());
	}
```

2024-01-29 12:26 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +public class ErrorHandler {
Во все методы обработчика нужно добавить логирование

2024-01-29 12:27 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.createFilm(film);
В методы контроллеров нужно добавить логирование

2024-01-29 12:28 UTC, VadimZharkov requested changes
Можно улучшить

2024-01-30 06:32 UTC, VadimZharkov approved these changes

2024-02-19 18:40 UTC, merged